import { type ReactNode, useCallback, useRef, useState } from 'react';
import { AccentKeys, AnswerInput, type AnswerInputHandle, Button } from '@/components';
import {
  decimalToWords,
  formatNumber,
  formatPrice,
  formatWeight,
  numberToWords,
  priceToWords,
  quantityToWords,
  THIN_SPACE,
} from '@/engine';
import type { PromptPayload, Verdict } from '@/session';
import type { DrillServices } from './types';

/* ------------------------------------------------------------------ *
 * Payload readers
 * ------------------------------------------------------------------ *
 * Every mode renders through these rather than switching on its own payload
 * kind: the round may replay a wrongQueue item generated by a *different* mode,
 * so a prompt must stay legible for any payload it is handed.
 */

/** What the payload looks like on screen: "1 234", "2,35 €", "250 g". */
export function promptDisplay(payload: PromptPayload): string {
  switch (payload.kind) {
    case 'number':
      return formatNumber(payload.value);
    case 'price':
      return formatPrice(payload.euros, payload.cents);
    case 'quantity': {
      const weight = formatWeight(payload.grams);
      // kg/g are the SI symbols in every UI language (no i18n key exists, and
      // inventing one would fork the price convention "2,35 €").
      return `${weight.value}${THIN_SPACE}${weight.unit}`;
    }
    case 'decimal':
      return `${formatNumber(payload.intPart)},${payload.fracDigits}`;
  }
}

/** How the payload is *said* in es-ES — the canonical spoken form. */
export function promptSpanish(payload: PromptPayload): string {
  switch (payload.kind) {
    case 'number':
      return numberToWords(payload.value);
    case 'price':
      return priceToWords(payload.euros, payload.cents).canonical;
    case 'quantity':
      return quantityToWords({ kind: 'weight', grams: payload.grams }).canonical;
    case 'decimal':
      return decimalToWords(payload.intPart, payload.fracDigits).canonical;
  }
}

/* ------------------------------------------------------------------ *
 * Prompt pieces
 * ------------------------------------------------------------------ */

/**
 * Numeral prompt sizes in px. The prompt is sized in the style attribute rather
 * than by class because it is chosen per value, so the two type tokens are
 * restated here: `xl` is --text-prompt-xl (the big numeral) and `lg` is
 * --text-prompt-lg (the price-tag-sized prompt). `wide`/`widest` are the two
 * step-downs drill-text.html applies past four digits — the scale has no token
 * for them.
 */
const PROMPT_PX = { xl: 92, wide: 64, widest: 48, lg: 56 } as const;

/** Digits past which the numeral steps down a size, so it still fits one line at 360px. */
const WIDE_DIGITS = 4;
const WIDEST_DIGITS = 6;

/**
 * Numeral prompt size (drill-text.html): full size up to four digits, then two
 * steps down so "999 999 999" still fits one line at 360px. Grouping thin
 * spaces do not count — only digits do.
 */
export function numeralFontSizePx(value: number): number {
  const digits = String(Math.abs(Math.trunc(value))).length;
  if (digits <= WIDE_DIGITS) return PROMPT_PX.xl;
  if (digits <= WIDEST_DIGITS) return PROMPT_PX.wide;
  return PROMPT_PX.widest;
}

export function NumeralPrompt({ payload }: { payload: PromptPayload }) {
  const text = promptDisplay(payload);
  const size = payload.kind === 'number' ? numeralFontSizePx(payload.value) : PROMPT_PX.lg;
  return (
    <div
      data-testid="numeral-prompt"
      className="font-bold font-display leading-none numerals"
      style={{ fontSize: `${size}px` }}
    >
      {text}
    </div>
  );
}

/** The 34px display-italic Spanish phrase (drill-digits / drill-choice). */
export function SpanishPhrase({ text }: { text: string }) {
  return (
    <p
      lang="es"
      data-testid="spanish-phrase"
      className="max-w-(--measure-prose) font-display font-medium text-spanish italic leading-[1.2]"
    >
      {text}
    </p>
  );
}

/** Centred stage column shared by every prompt zone. */
export function PromptStage({ children }: { children: ReactNode }) {
  return <div className="flex flex-col items-center gap-3.5 text-center">{children}</div>;
}

/**
 * "Speak this phrase when asked" — the play-on-demand state every audio prompt
 * needs: `speaking` is true for as long as the utterance runs (the pill disables
 * itself so a second tap cannot stack a second voice), and a rejected `speak`
 * is swallowed because a prompt that cannot be heard is not an error the learner
 * can act on — the drill still works with the phrase on screen.
 */
export function useSpeakOnDemand(
  services: DrillServices,
  text: string,
  slower: boolean,
): { speaking: boolean; speak: () => void } {
  const [speaking, setSpeaking] = useState(false);

  const speak = useCallback(() => {
    setSpeaking(true);
    services
      .speak(text, { slower })
      .catch(() => undefined)
      .finally(() => setSpeaking(false));
  }, [services, text, slower]);

  return { speaking, speak };
}

/* ------------------------------------------------------------------ *
 * Typed answer zone
 * ------------------------------------------------------------------ */

export interface TypedAnswerProps {
  /** Resets the field whenever the drill moves to another question. */
  questionId: string;
  mode: 'words' | 'digits';
  placeholder: string;
  submitLabel: string;
  verdict: Verdict | null;
  onSubmit: (given: string) => void;
  /** Diacritic row — word answers only (digits never need it). */
  accentKeys: boolean;
}

/**
 * Text/number answer zone: field + optional accent keys + the "Проверить" CTA.
 *
 * The CTA belongs to the answer zone because {@link AnswerZoneProps} exposes no
 * value to lift — the zone owns the draft and hands over a finished string. Once
 * a verdict lands the zone freezes and drops its CTA: the "Дальше" button in the
 * same slot is the drill's, not the mode's.
 */
export function TypedAnswer({
  questionId,
  mode,
  placeholder,
  submitLabel,
  verdict,
  onSubmit,
  accentKeys,
}: TypedAnswerProps) {
  const inputRef = useRef<AnswerInputHandle>(null);
  // Draft is keyed by question id and reset during render (no effect, no flash).
  const [entry, setEntry] = useState({ id: questionId, value: '' });
  if (entry.id !== questionId) setEntry({ id: questionId, value: '' });

  const answered = verdict !== null;
  const draft = entry.id === questionId ? entry.value : '';
  const ready = draft.trim() !== '' && !answered;

  function submit() {
    if (ready) onSubmit(draft.trim());
  }

  return (
    <div className="flex flex-col gap-3">
      <AnswerInput
        ref={inputRef}
        value={draft}
        onChange={(value) => setEntry({ id: questionId, value })}
        onSubmit={submit}
        mode={mode}
        placeholder={placeholder}
        aria-label={placeholder}
        {...(verdict !== null ? { verdict } : {})}
      />
      {accentKeys && !answered && (
        <AccentKeys onInsert={(char) => inputRef.current?.insertAtCaret(char)} />
      )}
      {!answered && (
        <Button type="button" disabled={!ready} onClick={submit}>
          {submitLabel}
        </Button>
      )}
    </div>
  );
}
