import { type ReactNode, useRef, useState } from 'react';
import { AccentKeys, AnswerInput, type AnswerInputHandle, Button } from '@/components';
import {
  decimalToWords,
  formatNumber,
  formatPrice,
  formatWeight,
  numberToWords,
  priceToWords,
  quantityToWords,
} from '@/engine';
import type { PromptPayload, Verdict } from '@/session';

/** U+2009 THIN SPACE — the separator the engine uses before a unit. */
const THIN_SPACE = ' ';

/* ------------------------------------------------------------------ *
 * Payload readers
 * ------------------------------------------------------------------ *
 * Every mode renders through these rather than switching on its own payload
 * kind: the round may replay a wrongQueue item generated by a *different* mode,
 * so a prompt must stay legible for any payload it is handed.
 */

/** What the payload looks like on screen: "1 234", "2,35 €", "250 g". */
export function promptDisplay(payload: PromptPayload): string {
  switch (payload.kind) {
    case 'number':
      return formatNumber(payload.value);
    case 'price':
      return formatPrice(payload.euros, payload.cents);
    case 'quantity': {
      const weight = formatWeight(payload.grams);
      // kg/g are the SI symbols in every UI language (no i18n key exists, and
      // inventing one would fork the price convention "2,35 €").
      return `${weight.value}${THIN_SPACE}${weight.unit}`;
    }
    case 'decimal':
      return `${formatNumber(payload.intPart)},${payload.fracDigits}`;
  }
}

/** How the payload is *said* in es-ES — the canonical spoken form. */
export function promptSpanish(payload: PromptPayload): string {
  switch (payload.kind) {
    case 'number':
      return numberToWords(payload.value);
    case 'price':
      return priceToWords(payload.euros, payload.cents).canonical;
    case 'quantity':
      return quantityToWords({ kind: 'weight', grams: payload.grams }).canonical;
    case 'decimal':
      return decimalToWords(payload.intPart, String(payload.fracDigits)).canonical;
  }
}

/* ------------------------------------------------------------------ *
 * Prompt pieces
 * ------------------------------------------------------------------ */

/**
 * Numeral prompt size (drill-text.html): --text-prompt-xl (92px) up to four
 * digits, then two steps down so "999 999 999" still fits one line at 360px.
 * Grouping thin spaces do not count — only digits do.
 */
export function numeralFontSizePx(value: number): number {
  const digits = String(Math.abs(Math.trunc(value))).length;
  if (digits <= 4) return 92;
  if (digits <= 6) return 64;
  return 48;
}

export function NumeralPrompt({ payload }: { payload: PromptPayload }) {
  const text = promptDisplay(payload);
  const size = payload.kind === 'number' ? numeralFontSizePx(payload.value) : 56;
  return (
    <div
      data-testid="numeral-prompt"
      className="font-bold font-display leading-none numerals"
      style={{ fontSize: `${size}px` }}
    >
      {text}
    </div>
  );
}

/** The 34px display-italic Spanish phrase (drill-digits / drill-choice). */
export function SpanishPhrase({ text }: { text: string }) {
  return (
    <p
      lang="es"
      data-testid="spanish-phrase"
      className="max-w-[19.375rem] font-display font-medium text-spanish italic leading-[1.2]"
    >
      {text}
    </p>
  );
}

/** 13px speaker glyph for the "прослушать" pill. */
export function SpeakerGlyph() {
  return (
    <svg
      width="13"
      height="13"
      viewBox="0 0 24 24"
      fill="none"
      aria-hidden="true"
      focusable="false"
    >
      <path d="M4 9.5v5h3.5L13 19V5L7.5 9.5H4z" fill="currentColor" />
      <path
        d="M15.5 8.5a5 5 0 010 7M17.8 6.2a8.2 8.2 0 010 11.6"
        stroke="currentColor"
        strokeWidth="1.8"
        strokeLinecap="round"
      />
    </svg>
  );
}

/** Centred stage column shared by every prompt zone. */
export function PromptStage({ children }: { children: ReactNode }) {
  return <div className="flex flex-col items-center gap-3.5 text-center">{children}</div>;
}

/* ------------------------------------------------------------------ *
 * Typed answer zone
 * ------------------------------------------------------------------ */

export interface TypedAnswerProps {
  /** Resets the field whenever the drill moves to another question. */
  questionId: string;
  mode: 'words' | 'digits';
  placeholder: string;
  submitLabel: string;
  verdict: Verdict | null;
  onSubmit: (given: string) => void;
  /** Diacritic row — word answers only (digits never need it). */
  accentKeys: boolean;
}

/**
 * Text/number answer zone: field + optional accent keys + the "Проверить" CTA.
 *
 * The CTA belongs to the answer zone because {@link AnswerZoneProps} exposes no
 * value to lift — the zone owns the draft and hands over a finished string. Once
 * a verdict lands the zone freezes and drops its CTA: the "Дальше" button in the
 * same slot is the drill's, not the mode's.
 */
export function TypedAnswer({
  questionId,
  mode,
  placeholder,
  submitLabel,
  verdict,
  onSubmit,
  accentKeys,
}: TypedAnswerProps) {
  const inputRef = useRef<AnswerInputHandle>(null);
  // Draft is keyed by question id and reset during render (no effect, no flash).
  const [entry, setEntry] = useState({ id: questionId, value: '' });
  if (entry.id !== questionId) setEntry({ id: questionId, value: '' });

  const answered = verdict !== null;
  const draft = entry.id === questionId ? entry.value : '';
  const ready = draft.trim() !== '' && !answered;

  function submit() {
    if (ready) onSubmit(draft.trim());
  }

  return (
    <div className="flex flex-col gap-3">
      <AnswerInput
        ref={inputRef}
        value={draft}
        onChange={(value) => setEntry({ id: questionId, value })}
        onSubmit={submit}
        mode={mode}
        placeholder={placeholder}
        aria-label={placeholder}
        {...(verdict !== null ? { verdict } : {})}
      />
      {accentKeys && !answered && (
        <AccentKeys onInsert={(char) => inputRef.current?.insertAtCaret(char)} />
      )}
      {!answered && (
        <Button type="button" disabled={!ready} onClick={submit}>
          {submitLabel}
        </Button>
      )}
    </div>
  );
}
